# subscriber image

# This is a will create a basic subscriber that
# will subscribe to a simple text topic

FROM rosbasic

COPY subscriber.py /catkin_ws/src/master_pkg/src/subscriber.py

ADD  run_subscriber.sh run_subscriber.sh
CMD ./run_subscriber.sh
