
version: '3.7'

services:

  rosbasic:
    build:
      context: ./rosbasic
      dockerfile: Dockerfile

  roscore:
    build:
      context: ./roscore
      dockerfile: Dockerfile
    image: roscore
    ports:
      - "11311:11311"
    environment:
      LOCALIP: 10.0.1.5
      DISPLAY: $LOCALIP:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    command: "./run_roscore.sh"

  turtlesim:
    build:
      context: ./turtlesim
      dockerfile: Dockerfile
    image: turtlesim
    environment:
      LOCALIP: 10.0.1.5
      ROS_MASTER_URI: http://$LOCALIP:11311/
      ROS_HOSTNAME: Marks-iMac.local
      DISPLAY: $LOCALIP:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    
#  turtlesimkey:
#    build:
#      context: ./turtlesim
#      dockerfile: Dockerfile
#    image: turtlesim
#    environment:
#      LOCALIP: 10.0.1.5
#      ROS_MASTER_URI: http://$LOCALIP:11311/
#      DISPLAY: $LOCALIP:0
#    volumes:
#      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
#    command: "rosrun turtlesim turtlesim_teleop_key"