
version: '3.7'

services:

  roscore:
    build:
      context: ./roscore
      dockerfile: Dockerfile
    image: roscore
    ports:
      - "11311:11311"
    environment:
      LOCALIP: 10.0.1.5
      DISPLAY: $LOCALIP:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    command: roscore

  picam:
    build:
      context: ./picam
      dockerfile: Dockerfile
    image: picam
    environment:
      LOCALIP: 10.0.1.5
      ROS_MASTER_URI: http://$LOCALIP:11311/
      DISPLAY: $LOCALIP:0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
    command: 'python /catkin_ws/src/picam/testnode.py'