# subscriber image

# This is a will create a basic subscriber that
# will subscribe to a simple text topic

FROM rosbasic

COPY picam_subscriber.py /catkin_ws/src/master_pkg/src/picam_subscriber.py

ADD  run.sh run.sh
CMD ./run.sh
