# publisher image

# This is a will create a basic publisher that
# will publish a simple text message

FROM rosbasic

COPY publisher.py /catkin_ws/src/master_pkg/src/publisher.py

ADD  run_publisher.sh run_publisher.sh
CMD ./run_publisher.sh
